version: "3"
services:
  db:
    container_name: storytestdb
    image: mysql:latest
    restart: always
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "stori"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  app:
    container_name: storitest
    depends_on:
      - "db"
    build: ./
    command: sh -c "sleep 10s ; python ./main.py"
