version: "3"
services:
  db:
    container_name: storytestdb
    image: mysql:latest
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "stori"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "storytestdb"]
          timeout: 20s
          retries: 10
  app:
    container_name: storitest
    depends_on:
      db:
        condition: service_healthy
    build: ./
    command: sh -c "sleep 10s ; python ./main.py"
